name: Run pytests
on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  call-pytest-test:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      pytest_cov_dir: solar_and_storage
      python-version: "['3.10']"
      python_path: './solar_and_storage'
      os_list: '["ubuntu-latest"]'

